import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,mkdir,rm} from 'node:fs/promises';
import {resolve} from 'node:path';
import {dates,aggregate,request,collect} from '../src/data.mjs';
import {hero,xml,mergeReadme,validateConfig,readme} from '../src/render.mjs';
import {generate} from '../src/generate.mjs';
const config=JSON.parse(await readFile(new URL('../profile.config.json',import.meta.url),'utf8'));
const days=dates(new Date('2026-10-09T12:00:00Z'));
const connection=nodes=>({nodes,pageInfo:{hasNextPage:false}});
const group=(isPrivate,nodes)=>({repository:{isPrivate},contributions:connection(nodes)});
function collection(){return {commitContributionsByRepository:[],issueContributionsByRepository:[],pullRequestContributionsByRepository:[],pullRequestReviewContributionsByRepository:[],repositoryContributions:connection([])};}
const node={occurredAt:'2026-10-09T04:00:00Z',commitCount:3};
test('30 UTC days span month, year and leap-day boundaries',()=>{
 assert.equal(days.length,30);assert.equal(days[0],'2026-09-10');assert.equal(days.at(-1),'2026-10-09');
 assert.ok(dates(new Date('2024-03-01Z')).includes('2024-02-29'));
 assert.equal(dates(new Date('2026-01-02Z'))[0],'2025-12-04');
});
test('only explicitly public repositories enter totals',()=>{
 const c=collection();c.commitContributionsByRepository=[group(false,[node]),group(true,[{...node,commitCount:999}]),group(undefined,[node])];
 c.issueContributionsByRepository=[group(false,[node])];
 c.repositoryContributions=connection([{...node,repository:{isPrivate:false}},{...node,repository:{isPrivate:true}}]);
 assert.equal(aggregate(c,days).at(-1).count,5);
});
test('refuse truncated groups and pages instead of publishing partial data',()=>{
 const c=collection();c.issueContributionsByRepository=Array(100).fill(group(false,[]));assert.throws(()=>aggregate(c,days));
 const d=collection();d.repositoryContributions.pageInfo.hasNextPage=true;assert.throws(()=>aggregate(d,days));
});
test('invalid counts fail closed',()=>{const c=collection();c.commitContributionsByRepository=[group(false,[{...node,commitCount:-1}])];assert.throws(()=>aggregate(c,days));});
test('missing dates become real zeroes and out-of-window data is excluded',()=>{
 const c=collection();c.commitContributionsByRepository=[group(false,[{...node,occurredAt:'2020-01-01T00:00:00Z'}])];
 assert.ok(aggregate(c,days).every(d=>d.count===0));
});
test('HTTP and GraphQL errors reject without leaking response bodies',async()=>{
 await assert.rejects(request('https://example.test',{},async()=>({ok:false,status:401})),/HTTP 401/);
 await assert.rejects(request('https://example.test',{},async()=>({ok:true,json:async()=>({errors:[{message:'private details'}]})})),/GraphQL returned errors/);
});
test('missing token rejects',async()=>{await assert.rejects(collect(config,''),/required/);});
test('SVG escaping, zero baseline, both themes and reduced motion',()=>{
 const data={contributions:aggregate(collection(),days),asOf:days.at(-1)};
 const svg=hero({...config,title:'<script>&'},data);
 assert.ok(svg.includes('&lt;script&gt;&amp;'));assert.ok(!svg.includes('NaN'));
 assert.ok(svg.includes('prefers-reduced-motion:reduce'));assert.ok(svg.includes('animation:none'));
 assert.ok(hero(config,data,'dark').includes('#0d1117'));
 assert.equal(xml('"'), '&quot;');
});
test('preserve existing README and replace only owned block',()=>{
 assert.equal(mergeReadme('My original text','<!-- vernal:start -->x<!-- vernal:end -->'),'My original text\n\n<!-- vernal:start -->x<!-- vernal:end -->');
 assert.equal(mergeReadme('before<!-- vernal:start -->old<!-- vernal:end -->after','<!-- vernal:start -->new<!-- vernal:end -->'),'before<!-- vernal:start -->new<!-- vernal:end -->after');
 assert.throws(()=>mergeReadme('<!-- vernal:start -->','x'));
});
test('configuration rejects URL injection',()=>{assert.throws(()=>validateConfig({...config,projects:[{repo:'../secrets'}]}));});
test('README has accessible native project links',()=>{
 const data={contributions:aggregate(collection(),days),asOf:days.at(-1),projects:config.projects.map(p=>({...p,url:'https://github.com/'+p.repo,language:'Code'}))};
 assert.ok(readme(config,data).includes('[Videoder](https://github.com/Cydiacoft/Videoder)'));
});
test('failed fetch preserves every previously generated byte',async()=>{
 const work=resolve('work');await mkdir(work,{recursive:true});const root=await mkdtemp(resolve(work,'test-'));
 try{await mkdir(resolve(root,'assets'));await writeFile(resolve(root,'profile.config.json'),JSON.stringify(config));
 for(const file of ['README.md','assets/hero-light.svg','assets/hero-dark.svg'])await writeFile(resolve(root,file),'old-'+file);
 await assert.rejects(generate(root,{token:'test',fetcher:async()=>({ok:false,status:401})}));
 for(const file of ['README.md','assets/hero-light.svg','assets/hero-dark.svg'])assert.equal(await readFile(resolve(root,file),'utf8'),'old-'+file);
 }finally{await rm(root,{recursive:true,force:true});}
});
test('REST rejects private project metadata',async()=>{
 let n=0;
 await assert.rejects(collect(config,'test',new Date('2026-10-09T12:00:00Z'),async()=>({ok:true,json:async()=>++n===1?{data:{user:{contributionsCollection:collection()}}}:{private:true}})),/not verified public/);
});
